# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15y5muaLCXiA7C7fbLMr_bAO9bgCKj9bv
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from openai import OpenAI
import os

# =========================
# Load Saved Files
# =========================

@st.cache_resource
def load_models():
    regression_model = joblib.load("regression_model.pkl")
    classifier_model = joblib.load("classifier_model.pkl")
    scaler = joblib.load("scaler.pkl")
    model_columns = joblib.load("model_columns.pkl")
    num_cols = joblib.load("num_cols.pkl")
    return regression_model, classifier_model, scaler, model_columns, num_cols

xgb_model, classifier_model, scaler, model_columns, num_cols = load_models()

# =========================
# Groq Setup
# =========================

client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)

def get_llm_explanation(price, category, bedrooms, bathrooms, sqft_living):
    prompt = f"""
    A house price prediction system produced:

    Predicted Price: {price:.2f} USD
    Market Category: {category}

    Bedrooms: {bedrooms}
    Bathrooms: {bathrooms}
    Living Area: {sqft_living} sqft

    Explain why the model predicted this price.
    Explain why it belongs to this market category.
    """

    response = client.chat.completions.create(
        model="llama3-70b-8192",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3
    )

    return response.choices[0].message.content

# =========================
# Streamlit UI
# =========================

st.title("🏡 AI Real Estate Prediction System")

st.sidebar.header("Enter House Details")

bedrooms = st.sidebar.number_input("Bedrooms", 1, 20, 3)
bathrooms = st.sidebar.number_input("Bathrooms", 1, 10, 2)
sqft_living = st.sidebar.number_input("Living Area (sqft)", 100, 20000, 1500)
sqft_lot = st.sidebar.number_input("Lot Area (sqft)", 500, 100000, 5000)
floors = st.sidebar.number_input("Floors", 1, 5, 1)
waterfront = st.sidebar.selectbox("Waterfront", [0, 1])
view = st.sidebar.slider("View (0-4)", 0, 4, 0)
condition = st.sidebar.slider("Condition (1-5)", 1, 5, 3)
sqft_above = st.sidebar.number_input("Sqft Above Ground", 100, 20000, 1200)
sqft_basement = st.sidebar.number_input("Sqft Basement", 0, 10000, 300)
yr_built = st.sidebar.number_input("Year Built", 1900, 2026, 2000)
yr_renovated = st.sidebar.number_input("Year Renovated", 0, 2026, 0)
year = st.sidebar.number_input("Sale Year", 2000, 2026, 2014)
month = st.sidebar.slider("Sale Month", 1, 12, 6)
day = st.sidebar.slider("Sale Day", 1, 31, 15)

if st.button("Predict"):

    input_data = pd.DataFrame({
        'bedrooms':[bedrooms],
        'bathrooms':[bathrooms],
        'sqft_living':[sqft_living],
        'sqft_lot':[sqft_lot],
        'floors':[floors],
        'waterfront':[waterfront],
        'view':[view],
        'condition':[condition],
        'sqft_above':[sqft_above],
        'sqft_basement':[sqft_basement],
        'yr_built':[yr_built],
        'yr_renovated':[yr_renovated],
        'year':[year],
        'month':[month],
        'day':[day]
    })

    # Add missing dummy columns
    for col in model_columns:
        if col not in input_data.columns:
            input_data[col] = 0

    input_data = input_data[model_columns]

    # Scale numeric columns
    input_data[num_cols] = scaler.transform(input_data[num_cols])

    # ===== Regression =====
    predicted_price = float(xgb_model.predict(input_data)[0])

    # ===== Classification =====
    cluster_prediction = classifier_model.predict(input_data)[0]

    cluster_names = {
        0: 'Upper-Middle',
        1: 'Mid-Range',
        2: 'Budget',
        3: 'Luxury'
    }

    category = cluster_names.get(cluster_prediction, "Unknown")

    st.subheader(f"Predicted Price: ${predicted_price:,.2f}")
    st.write(f"Market Category: **{category}**")

    if st.button("Get AI Explanation"):
        explanation = get_llm_explanation(
            predicted_price,
            category,
            bedrooms,
            bathrooms,
            sqft_living
        )
        st.markdown("### 💡 AI Explanation")
        st.write(explanation)